type User {
    _id: ID
    name: String!
    surname: String!
    email: String!
    password: String!
}

type Customer {
    _id: ID
    name: String!
    surname: String!
    email: String!
    phone: String!
    bookDescription: String!
    bookPrice: Float,
    purchaseDate: String,
    isbn: String!
}

type Token {
    token: String!
}

type Query {
    User: User
    Customers: [Customer]
}

type Mutation {
    addCustomer(
        name: String!
        surname: String!
        email: String!
        phone: String!
        bookDescription: String!
        bookPrice: Float,
        purchaseDate: String,
        isbn: String!
    ): Customer!,
    updateCustomer(
        _id: String!
        name: String!
        surname: String!
        email: String!
        phone: String!
        bookDescription: String!
        bookPrice: Float,
        purchaseDate: String,
        isbn: String!
        ): Customer!,
    signInUser(email: String!, password: String!): Token
    signUpUser(name: String!, surname: String!, email: String!, password: String!): Token,
}